config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods, only: [:create, :destroy]
  devise_for :users

  resources :recipes
  get '/public_recipes', to: 'recipes#public'
  resources :users do
    resources :foods
  end

  resources :public_recipes, only: %i[index]
  resources :shopping_lists, only: %i[index]
  resources :recipe_foods, only: %i[new create destroy]
  
  root 'recipes#public'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, Recipe, public: true
    return unless user.present?

    can :manage, Recipe, user: user
    can :manage, RecipeFood do |ingredient|
      ingredient.recipe.user == user
    end

    can :manage, Food, user: user
    can :read, :all
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
  validates :name, :measurement_unit, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, :preparation_time, :cooking_time, :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password)
    end

    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password, :remember_me)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(
      name: food_params[:name],
      measurement_unit: food_params[:measurement_unit],
      price: food_params[:price],
      user_id: current_user.id
    )

    if @food.save
      redirect_to user_foods_path(current_user.id)
      flash[:success] = 'Food saved successfully'
    else
      render :new
      flash.now[:error] = 'Food not saved'
    end
  end

  def destroy
    @food = Food.find(params[:id])

    redirect_to user_foods_path(current_user.id)
    if @food.destroy
      flash[:success] = 'Food deleted successfully'
    else
      flash.now[:error] = 'Food not deleted'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello; end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def create
    recipe_foods = RecipeFood.new(quantity: params[:quantity])
    recipe_foods.food_id = params[:food_id]
    recipe_foods.recipe_id = params[:recipe_id]
    recipe_foods.save
    redirect_to recipe_path(params[:recipe_id])
    flash[:notice] = 'Ingredient added successfully'
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:public]
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])

    @ingredients = RecipeFood.where(recipe_id: @recipe.id)
    @foods = Food.where(id: @ingredients.map(&:food_id))
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, alert: 'An error has occurred while creating the recipt, try again' }
      end
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
      else
        format.html { render :edit, alert: 'An error has occurred while updating the recipt' }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
    end
  end

  def public
    @public_recipes = Recipe.where(public: true)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @recipes = Recipe.all
    @ingredients = RecipeFood.where(recipe_id: @recipes.map(&:id))
    @foods = Food.where(id: @ingredients.map(&:food_id))
  end

  def total_price
    price = 0
    @ingredients.each do |recipe_food|
      price += Food.find(recipe_food.food_id).price * recipe_food.quantity
    end
    price
  end

  helper_method :total_price
  
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
    @ingredients = RecipeFood.where(recipe_id: @recipes.map(&:id))
    @foods = Food.where(id: @ingredients.map(&:food_id))
  end

  def total_price
    price = 0
    @ingredients.each do |recipe_food|
      price += Food.find(recipe_food.food_id).price * recipe_food.quantity
    end
    price
  end

  helper_method :total_price
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/foods/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h1>Food</h1>
    <div>
      <%= link_to "Add food", new_user_food_path(current_user.id), class: "btn btn-outline-success btn-sm" %>
    </div>
  </div>
<div>
 <table class="table table-striped table-hover">
  <thead class="table-light"> 
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

        <% @foods.each do |food| %>
    <tr>
      <td><%=food.name%></td>
      <td><%=food.measurement_unit%></td>
      <td>$ <%=food.price%></td>
      <td>      
        <% if can? :manage, food%>
          <%=button_to "Delete", "/users/#{current_user.id}/foods/#{food.id}",
            :method=>:delete, :data=>{turbo:false}, class: "btn btn-outline-danger btn-sm" %> 
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
 </table>
 
</div>



app/views/foods/new.html.erb
<h1>Add new food</h1>

<%= form_with model: @food, url: "/users/#{current_user.id}/foods" do |f| %>

<div>
    <div class="form-group">
      <%= f.label :Name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Measurement_Unit  %>
      <%= f.select :measurement_unit, ['grams', 'kilograms', 'units', 'litres', 'dozen'],
       {}, {class: "form-select"} %>
    </div>

    <div class="form-group">
      <%= f.label :Price %>
      <%= f.number_field :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit %>
    </div>
  </div>

<% end%>

app/views/recipe_foods/_recipe_food_form.html.erb
<!-- Modal -->
<div class="d-flex w-100 h-100 d-none fixed-top justify-content-center align-items-center popup" id="toggleModel">
  <div class="card text-center w-50">
    <div class="card-header">
      Add Ingredient
    </div>
    <%= form_with url: recipe_foods_path({recipe_id: @recipe.id}) do |form|%>
      <div class="card-body">
        <div class="d-flex flex-column mb-2">
          <%= form.label "Food", class:"form-label" %>
          <%= form.collection_select :food_id, Food.order(:name),:id,:name, include_blank: true, class:"form-select" %>
        </div>
        <div class="d-flex flex-column">
          <%= form.label :quantity, class:"form-label" %>
          <%= form.number_field :quantity, class:"form-control" %>
        </div>
      </div>
      <div class="card-footer text-muted">
        <div class="d-flex justify-content-end">
          <button type="button" class="btn btn-secondary mx-3" onclick="(() => {
            document.getElementById('toggleModel').classList.toggle('d-none')
            })()">Cancel</button>
          <button class="btn btn-success" type="submit">Add</button>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <ul>
      <% recipe.errors.each do |error| %>
        <li class="alert alert-danger" role="alert"><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter name" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :preparation_time %>
    <%= form.text_field :preparation_time, class: "form-control", placeholder: "Enter preparation time" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :cooking_time %>
    <%= form.text_field :cooking_time, class: "form-control", placeholder: "Enter cooking time" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", placeholder: "Enter description", rows:"5" %>
  </div>
  <br>
  <div class="form-check">
    <%= form.check_box :public ,class: "form-check-input"%>
    <%= form.label :public, class:"form-check-label" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
     <td><%= recipe.name %></td>
      <td><%= recipe.preparation_time %></td>
      <td><%= recipe.cooking_time %></td>
      <td><%= recipe.description %></td>

app/views/recipes/_recipe_header.html.erb
<thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Preparation time</th>
    <th scope="col">Cooking time</th>
    <th scope="col">Description</th>
    <th scope="col">Activity</th>
  </tr>
</thead>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>
<%= render "form", recipe: @recipe %>
<br>
<div>
  <%= link_to "Show this recipe", @recipe, class: "trans-link" %> |
  <%= link_to "Back to recipes", recipes_path ,class: "trans-link" %>
</div>

app/views/recipes/index.html.erb
<div>
  <% if flash[:notice] %>
    <p class="alert alert-success" role="alert"><%= notice %></p>
  <% end %>
  <div class="d-flex justify-content-between align-items-center">
    <h1>Recipes</h1>
    <div>
      <%= link_to "New recipe", new_recipe_path, class: "btn btn-outline-success btn-sm" %>
    </div>
  </div>
  <div id="recipes">
    <table class="table">
      <%= render partial: "recipe_header"  %>
      <tbody>
        <% @recipes.each do |recipe| %>
          <tr>
            <%= render recipe %>
            <td><%= link_to "Show", recipe, class: "btn btn-outline-primary btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>
<%= render "form", recipe: @recipe %>
<br>
<div>
  <%= link_to "🔙 Back", recipes_path, class: "btn btn-outline-secondary btn-sm"%>
</div>

app/views/recipes/public.html.erb
<h1 class="d-flex justify-content-center">Public recipes</h1>
<div>
  <% @public_recipes.each do |recipe| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title d-flex justify-content-center"><%= recipe.name.capitalize %> recipe</h5>
        <div class="d-flex justify-content-between m-2">
          <div>
            <p class="card-text">Total food Items: <%= RecipeFood.where(recipe_id: recipe.id).count %></p>
            <p class="card-text">Total price: <%= RecipeFood.where(recipe_id: recipe.id).reduce(0) { |sum, f| sum + (f.quantity*Food.find(f.food_id).price).to_f } %></p>
            <p class="card-text"><span class="fst-italic">Made by: </span><small class="text-muted"><%= User.find_by(id: recipe.user_id).name %></small></p>
            <% if can? :manage, recipe%>
              <%= link_to "Details",recipe ,class: "fst-italic"  %>
            <% end %>
          </div>
          <div class="form-check form-switch">
            <% if can? :manage, recipe %>
              <%= button_to "Destroy", recipe, method: :delete, class: "btn btn-outline-danger btn-sm small-btn"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div>
  <% if flash[:notice] %>
    <p class="alert alert-success" role="alert"><%= notice %></p>
  <% end %>
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title d-flex justify-content-center"><%= @recipe.name.capitalize %> recipe</h5>
      <div class="d-flex justify-content-between m-2">
        <div>
          <p class="card-text">Description: <%= @recipe.description %></p>
          <p class="card-text"><small class="text-muted">Cooking time: <%= @recipe.cooking_time %></small></p>
          <p class="card-text"><small class="text-muted">Preparation time: <%= @recipe.preparation_time %></small></p>
        </div>
        <div class="form-check form-switch">
          <% if can? :manage, @recipe %>
            <%= form_with(model: @recipe) do |form| %>
              <%= form.check_box :public,onchange: 'this.form.submit();',class:"form-check-input"%>
              <label class="form-check-label" for="flexSwitchCheckDefault">public</label>
            <% end %>
            <div class="d-flex gap-2" style="margin:20px 0 0 -40px;"><%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-outline-primary btn-sm" %>  <%= button_to "Destroy", @recipe, method: :delete, class: "btn btn-outline-danger btn-sm small-btn"%></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-between">
    <%= link_to "🔙 Back to recipes", recipes_path, class: "btn btn-outline-secondary btn-sm"%>
    <% if can? :manage, @recipe%>
      <button class="btn btn-success" id="addIngredient" data-toggle="modal" data-target="#exampleModal" onclick="(() => {
        document.getElementById('toggleModel').classList.toggle('d-none')
        })()">Add ingredient</button>
    <% else %>
      <button class="btn btn-success" disabled id="addIngredient" data-toggle="modal" data-target="#exampleModal" onclick="(() => {
        document.getElementById('toggleModel').classList.toggle('d-none')
        })()">Add ingredient</button>
    <% end %>
  </div>
  <div class="border rounded-3 mt-3 p-3 ">
    <div class=" align-items-center">
      <h3 class="p-2">ingredients</h3>
    </div>
    <div id="shopping-list">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Food</th>
            <th scope="col">Quantity</th>
            <th scope="col">Price</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <%= render "shopping_lists/shopping_list" %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render partial: "recipe_foods/recipe_food_form" %>

app/views/shopping_lists/_shopping_list.html.erb
<% @foods.each do |food| %>
  <tr>
    <% quantity = RecipeFood.joins(:food).where(food_id: food.id).sum('quantity') %>
    <td><%= food.name %></td>
    <td><%= quantity %> <%= food.measurement_unit %> </td>
    <td>$ <%= food.price * quantity %></td>
    <td class="d-flex gap-2">
      <button class="btn btn-primary btn-sm" disabled>
        Edit
      </button>
      <button class="btn btn-danger btn-sm" disabled>
        Destroy
      </button>
    </td>
  </tr>
<% end %>

app/views/shopping_lists/index.html.erb
<div>
  <% if flash[:notice] %>
    <p class="alert alert-success" role="alert"><%= notice %> </p>
  <% end %>
  <div class="d-flex justify-content-between align-items-center">
    <h1>General Shopping list</h1>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item">Amount of food items to buy: <%= @ingredients.count %> </li>
      <li class="list-group-item"> Total value of food needed: $ <%= total_price %> </li>
    </ul>
  </div>
  <div id="shopping-list">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
        <%= render "shopping_list" %>
      </tbody>
    </table>
  </div>

</div>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>